### ISSUE TITLE
Waiting for the code

### ISSUE THREAD

**Issue by echo-sky** [noahcao/OC_SORT#1] opened 2022-03-29 06:38 UTC
The code is not available now. Look forward to access the code as soon as possible.
 Thanks to the author.

**Comment by oconnor127** [comment] 2022-03-29 11:19
+1

**Comment by YamacTan** [comment] 2022-03-29 14:43
+1. Following for updates.

**Comment by vovantuan1999a** [comment] 2022-03-30 04:32
+1. Following for updates

**Comment by dattv** [comment] 2022-03-31 05:19
+1

**Comment by Mobu59** [comment] 2022-04-02 03:34
mark!

**Comment by noahcao** [comment] 2022-04-02 19:07
Thanks everyone for paying attention to OC-SORT. I have released a preview version. The code is after cleanup and refactoring the code I used for the paper but I have re-validated reproducing the results in paper (see the [doc](https://github.com/noahcao/OC_SORT/blob/master/docs/GET_STARTED.md)) for details. 

This is a primary version as I am going to make [mmtracking](https://github.com/noahcao/mmtracking.git) to support OC-SORT with a better form, which is expected to be faster and more advanced. 

Please feel free to propose any issue if you have any questions or problems using the codebase. You can also reach out to me through jinkuncao@gmail.com

**Comment by noahcao** [comment] 2022-04-02 19:11
I will suspect there is still some little issues inside the current version. Also, because of the submission limitation, I haven't validated the results on KITTI/CroHD yet. Please let me know if you encounter any issues.

Moreover, the public tracking on MOT17/MOT20 which requires "detection filtering" is not included in this version either. I will try to make some time for that soon.

**Comment by noahcao** [comment] 2022-04-04 15:22
I'm closing this issue. Feel free to open a new issue for problems in the released code.

**Closed by noahcao** 2022-04-04 15:22 UTC
